// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	solutions "github.com/cloud-native-toolkit/itzcli/pkg/solutions"
	mock "github.com/stretchr/testify/mock"
)

// FilterOptions is an autogenerated mock type for the FilterOptions type
type FilterOptions struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *FilterOptions) Execute(_a0 *solutions.Filter) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewFilterOptions interface {
	mock.TestingT
	Cleanup(func())
}

// NewFilterOptions creates a new instance of FilterOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFilterOptions(t mockConstructorTestingTNewFilterOptions) *FilterOptions {
	mock := &FilterOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
