// Code generated by mockery v2.25.1. DO NOT EDIT.

package mocks

import (
	solutions "github.com/cloud-native-toolkit/itzcli/pkg/solutions"
	mock "github.com/stretchr/testify/mock"
)

// QueryOptions is an autogenerated mock type for the QueryOptions type
type QueryOptions struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *QueryOptions) Execute(_a0 *solutions.Query) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewQueryOptions interface {
	mock.TestingT
	Cleanup(func())
}

// NewQueryOptions creates a new instance of QueryOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQueryOptions(t mockConstructorTestingTNewQueryOptions) *QueryOptions {
	mock := &QueryOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
