language: go

env:
  global:
    - OCTOKIT_API_ENDPOINT="https://github.ibm.com/api/v3/"

go:
  - "1.19.x"

before_install:
  - scripts/write-netrc.sh
  
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "itzcli-darwin-amd64.tar.gz"
      - "itzcli-linux-amd64.tar.gz"
    skip_cleanup: true
    on:
      tags: true
      branch: main
  - provider: script
    script: bash scripts/deploy_public.sh $GITHUB_PUBLIC_TOKEN $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
      branch: main
