#!/usr/bin/env bash

set -eou pipefail

ATK_HOME=${HOME}/.atk
ATK_CLI=atkcli

if [ -f "./${ATK_CLI}" ]; then
  PATH=.:${PATH}
elif [ -f "${ATK_HOME}/bin/${ATK_CLI}" ]; then
  PATH=${ATK_HOME}/bin:${PATH}
fi

create_atk_config() {
  echo "${ATK_HOME} does not exist; creating..." >&2
  mkdir ${ATK_HOME}
  ${ATK_CLI} doctor init
  echo "Done." >&2
}

if [ ! -d "${ATK_HOME}" ]; then
  create_atk_config
fi

if [ ! $(command -v ${ATK_CLI}) ]; then
  # Install ATK if it is not already on the path
  echo "${ATK_CLI} command not found on your path; exiting." >&2
  exit 1
fi

$ATK_CLI $@
exit $?
