#!/usr/bin/env bash

set -eou pipefail

ITZ_HOME=${HOME}/.itz
ITZ_CLI=itzcli

if [ -f "./${ITZ_CLI}" ]; then
  PATH=.:${PATH}
elif [ -f "${ITZ_HOME}/bin/${ITZ_CLI}" ]; then
  PATH=${ITZ_HOME}/bin:${PATH}
fi

create_itz_config() {
  echo "${ITZ_HOME} does not exist; running doctor --auto-fix for the first time..." >&2
  mkdir ${ITZ_HOME}
  ${ITZ_CLI} doctor -f
}

if [ ! -d "${ITZ_HOME}" ]; then
  create_itz_config
fi

if [ ! $(command -v ${ITZ_CLI}) ]; then
  # Install ITZ if it is not already on the path
  echo "${ITZ_CLI} command not found on your path; exiting." >&2
  exit 1
fi

$ITZ_CLI "$@"
exit $?
