// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AuthHandlerFunc is an autogenerated mock type for the AuthHandlerFunc type
type AuthHandlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: req
func (_m *AuthHandlerFunc) Execute(req *http.Request) error {
	ret := _m.Called(req)

	var r0 error
	if rf, ok := ret.Get(0).(func(*http.Request) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthHandlerFunc creates a new instance of AuthHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthHandlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthHandlerFunc {
	mock := &AuthHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
