// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	atkmod "github.ibm.com/skol/atkmod"
)

// PreRunFunc is an autogenerated mock type for the PreRunFunc type
type PreRunFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: cli
func (_m *PreRunFunc) Execute(cli *atkmod.CliModuleRunner) error {
	ret := _m.Called(cli)

	var r0 error
	if rf, ok := ret.Get(0).(func(*atkmod.CliModuleRunner) error); ok {
		r0 = rf(cli)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPreRunFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewPreRunFunc creates a new instance of PreRunFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPreRunFunc(t mockConstructorTestingTNewPreRunFunc) *PreRunFunc {
	mock := &PreRunFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
