// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pkg "github.ibm.com/Nathan-Good/atkcli/pkg"
)

// ReservationFilter is an autogenerated mock type for the ReservationFilter type
type ReservationFilter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ReservationFilter) Execute(_a0 pkg.TZReservation) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(pkg.TZReservation) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewReservationFilter interface {
	mock.TestingT
	Cleanup(func())
}

// NewReservationFilter creates a new instance of ReservationFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReservationFilter(t mockConstructorTestingTNewReservationFilter) *ReservationFilter {
	mock := &ReservationFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
