// Code generated by mockery v2.25.1. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// ResponseHandlerFunc is an autogenerated mock type for the ResponseHandlerFunc type
type ResponseHandlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: reader
func (_m *ResponseHandlerFunc) Execute(reader io.ReadCloser) error {
	ret := _m.Called(reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.ReadCloser) error); ok {
		r0 = rf(reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewResponseHandlerFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewResponseHandlerFunc creates a new instance of ResponseHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewResponseHandlerFunc(t mockConstructorTestingTNewResponseHandlerFunc) *ResponseHandlerFunc {
	mock := &ResponseHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
