// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// VariableGetter is an autogenerated mock type for the VariableGetter type
type VariableGetter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: key
func (_m *VariableGetter) Execute(key string) (string, bool) {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

type mockConstructorTestingTNewVariableGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewVariableGetter creates a new instance of VariableGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVariableGetter(t mockConstructorTestingTNewVariableGetter) *VariableGetter {
	mock := &VariableGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
