// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	techzone "github.com/cloud-native-toolkit/itzcli/pkg/techzone"
	mock "github.com/stretchr/testify/mock"
)

// ReservationServiceClient is an autogenerated mock type for the ReservationServiceClient type
type ReservationServiceClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *ReservationServiceClient) Get(id string) (*techzone.Reservation, error) {
	ret := _m.Called(id)

	var r0 *techzone.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*techzone.Reservation, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *techzone.Reservation); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*techzone.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: f
func (_m *ReservationServiceClient) GetAll(f techzone.Filter) ([]techzone.Reservation, error) {
	ret := _m.Called(f)

	var r0 []techzone.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(techzone.Filter) ([]techzone.Reservation, error)); ok {
		return rf(f)
	}
	if rf, ok := ret.Get(0).(func(techzone.Filter) []techzone.Reservation); ok {
		r0 = rf(f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]techzone.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(techzone.Filter) error); ok {
		r1 = rf(f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReservationServiceClient creates a new instance of ReservationServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReservationServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReservationServiceClient {
	mock := &ReservationServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
