on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

name: Go build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Check out
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: make build
  test:
    needs: build
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Test
      run: make verify
